Margin            : 3cm  
LaTeX Input       : my-japanese-report-header  
Title             : <`1`>  
MajorHeading      : <`2`>  
MinorHeading      : <`3`>  
Author            : 杉本 元気  
Date              : <`4`>  
AssignmentDate    : <`5`>  
Base Header Level : 3  
LaTeX Input       : my-japanese-report-begin-doc  

